### ISSUE TITLE
fix license

### ISSUE THREAD

**Issue by Shamar** [wohper/monitorapk#2]
Ciao Wohper, sono felicissimo che tu abbia realizzato un tuo progetto su GitHub.

Tuttavia stai eseguendo codice sotto Hacking License per produrre i tuoi dataset, accettando la licenza.
Di conseguenza quei dataset sono sotto Hacking License ed il software che vi si basa deve essere sotto Hacking License.

La Hacking License è molto più virale degli altri copyleft perché richiede che sia applicata anche a tutti gli output del software che esegue.

Dunque per non essere in violazione del diritto d'autore, hai due strade: usare la Hacking License o usare un sistema completamente diverso (un qualsiasi formato dati a tua scelta, da csv a json...) che non comporti l'accettazione della Hacking License.
Ad esempio puoi usare curl per scaricare il dataset che desideri e awk per produrre un formato che ti piace.

Se scegli la prima strada, ti consiglio di specificare chiaramente nel README.md che la Hacking License è una licenza custom che ha questa caratteristica di applicarsi anche ai dati prodotti oltre che al software, come abbiamo fatto in Monitora PA https://github.com/MonitoraPA/monitorapa/#authors-copyright-and-licensing

Se invece prendi la seconda, puoi fare come ritieni più opportuno.

**Comment by wohper** [comment]
Gentilissimo, mai eseguito l'osservatorio. Garantiamo compatibilità con il formato dataset di MonitoraPA per gli utenti che volessero utilizzare quel progetto. Tutti i dataset che abbiamo utilizzato sono tsv scritti a mano. Un saluto.

**Comment by nemobis** [comment]
Se anche monitorapk contenesse codice per scaricare i TSV direttamente da https://monitora-pa.it/MonitoraPA_2022-08-01.zip , la GPL andrebbe benissimo.

Quei TSV non sono soggetti a copyright, o comunque non al copyright degli autori di MonitoraPA, perché stringhe come "1HA36SPJ" e indirizzi di posta elettronica non sono opere originali. Alcune colonne, per esempio in 101-consent.tsv, potenzialmente citano opere soggette a diritto d'autore, per esempio pezzi di temi ed estensioni, ma la licenza dei testi citati non si estende al complesso dei dati. (Se lo facesse, peraltro, la GPL sarebbe probabilmente piú compatibile, perché molte di quelle stringhe provengono da codice in GPL, come estensioni Wordpress.)

Se anche fossero soggetti a copyright, monitorapk non è un'opera derivata.

Quanto alla sussistenza di eventuali database rights, è dubbio se esistano sul complesso dei dati pubblicati da MonitoraPA, e in caso esistano a chi pertengano. La struttura complessiva di quei dati deriva da [IndicePA](https://www.indicepa.gov.it/ipa-portale/note-legali), che purtroppo non usa CC-0 ma CC-BY-3.0 (e non la versione it che rimuoverebbe i diritti sui generis). Anche se esistessero diritti sui generis, e appartenessero a Giacomo Tesio, non c'è nulla in questo archivio contro cui esercitarli: solo chi usasse quei database sarebbe soggetto ad azioni volte a esercitare tali ipotetici diritti. Prima di esercitare diritti sui generis contro tali ipotetici utenti potrebbe essere utile controllarne la giurisdizione, dato che fuori UE è particolarmente difficile esercitare i diritti sui generis.

**Comment by Shamar** [comment]
> Se anche monitorapk contenesse codice per scaricare i TSV direttamente da https://monitora-pa.it/MonitoraPA_2022-08-01.zip , la GPL andrebbe benissimo.

Per scaricarlo sì, ovviamente.

Utilizzarne i contenuti nei termini protetti dal diritto d'autore però richiede, ovviamente una accettazione della Hacking License con cui tali dati sono distribuiti.

Inoltre realizzare un software basato sullo specifico formato di [Monitora PA](https://github.com/MonitoraPA/monitorapa/blob/main/ARCHITETTURA.md) per facilitare tale utilizzo, renderebbe inequivocabilmente MonitoraPK un opera dipendente da MonitoraPA e dai dati che distribuisce sotto Hacking License. Ciò, nei termini **contrattuali** della Hacking License, impone l'utilizzo della Hacking License.

> Quei TSV non sono soggetti a copyright, o comunque non al copyright degli autori di MonitoraPA, perché stringhe come "1HA36SPJ" e indirizzi di posta elettronica non sono opere originali.

Lo è il formato in cui sono espressi, in uno specifico ordine delle colonne e con dei marcatori specificatamente scelti per le esigenze di Monitora PA come "Web" e "Email".

Inoltre quei TSV sono esplicitamente distribuiti sotto Hacking License, una licenza breve e di facile lettura che specifica esattamente le condizioni di utilizzo di ciascun file.

> La struttura complessiva di quei dati deriva da [IndicePA](https://www.indicepa.gov.it/ipa-portale/note-legali), che purtroppo non usa CC-0 ma CC-BY-3.0

Falso.

Il file enti.tsv incluso nell'archivio è scaricato dal sito di AgID ed incluso verbatim come propriamente documentato nel README.txt.

Tutti gli altri file sono opera di ingegno a sé stante ([documentata qui](https://github.com/MonitoraPA/monitorapa/blob/main/ARCHITETTURA.md)), cui si applica sia il copyright degli autori sia il diritto sui generis degli stessi in quanto esecutori dell'osservatorio sotto Hacking License che ha prodotto i dati contenuti nei file tsv aggiuntivi e non presenti nell'anagrafica AgID-IPA.

Gli autori infatti rispettano essi stessi la Hacking License nella propria interezza.

> Se anche fossero soggetti a copyright, monitorapk non è un'opera derivata.

Vero.

Ma per non violare il diritto d'autore degli autori di Monitora PA, non deve essere nemmeno un'opera **dipendente** da materiale protetto dalla Hacking License: infatti qualunque uso dei dati protetto dal diritto d'autore o da simili normative viene concesso agli utenti a valle dell'accettazione della licenza sia come contratto vincolante che come licenza.
Violando o non accettando il contratto, la licenza viene meno.
E laddove null'altro garantisca il diritto di utilizzo di dati o software sotto Hacking License, il loro utilizzo è una violazione del dei diritti detenuti dagli autori.

> Anche se esistessero diritti sui generis, e appartenessero a Giacomo Tesio, non c'è nulla in questo archivio contro cui esercitarli: solo chi usasse quei database sarebbe soggetto ad azioni volte a esercitare tali ipotetici diritti.  Prima di esercitare diritti sui generis contro tali ipotetici utenti potrebbe essere utile controllarne la giurisdizione, dato che fuori UE è particolarmente difficile esercitare i diritti sui generis.

Stai pubblicamente suggerendo di violare la normativa e i diritti degli autori di Monitora PA abusando la difficoltà di enforcement di tali diritti? E' una sorta di istigazione a violare i diritti di chi vi ha **donato** Monitora PA?

Al di là della normativa sul diritto d'autore @nemobis, questo non è esattamente lo stesso approccio che hanno i Titolari del Trattamento nei confronti del GDPR e dei diritti degli interessati?

**Comment by wohper** [comment]
Scusate, ma non ho capito una cosa. MonitoraPA scarica i dati da IndicePA che usa una specifica licenza:

https://github.com/MonitoraPA/monitorapa/blob/c1696a6460272930744806147b6319478dfd2449/cli/data/enti/download.py#L69

Come fai a trasformare  una CC-BY-3.0 nella hacking license? Non dovresti tu stesso rispettare la licenza originale? 

Affermi inoltre che lo specifico formato del file (un TSV di 3 colonne) sia protetto da copyright, ma a quanto mi risulta, nella nostra legislazione non è possibile proteggere questo tipo di invenzioni, come non è possibile sottoporre a brevetto un software, un formato file o una ricetta di cucina.

Puoi chiarire questi punti in modo comprensibile, citando la specifica legislazione a cui ti riferisci?

Grazie!

**Comment by nemobis** [comment]
È andata persa la risposta che ho mandato ieri.

> Stai pubblicamente suggerendo di violare la normativa e i diritti degli autori di Monitora PA abusando la difficoltà di enforcement di tali diritti?

Ovviamente no. Mi limito a segnalare che in giurisdizioni diverse si applicano norme diverse. I diritti sui database, in particolare, sono scarsamente armonizzati fuori dall'UE (e per fortuna!).

**Comment by wohper** [comment]
Cosa intendi per diritti sui database? La mia domanda è doppia, perché da una parte abbiamo i dati che vengono da una licenza ben specifica, dall'altra l'organizzazione di uno schema dati che non può (a quando ne so) essere oggetto di copyright in Europa.

**Comment by nemobis** [comment]
Il 09/09/22 23:44, Mark Wohper ha scritto:
> Cosa intendi per diritti sui database?

https://en.wikipedia.org/wiki/Database_right
https://en.wikipedia.org/wiki/Database_Directive

**Comment by wohper** [comment]
Grazie. Non è che sia chiarissimo a cosa si riferisca Tesio ma aspettiamo lumi,

**Comment by Shamar** [comment]
> Come fai a trasformare una CC-BY-3.0 nella hacking license? Non dovresti tu stesso rispettare la licenza originale?

A queste domande può rispondere facilmente un qualsiasi avvocato specializzato @wohper.

In generale, materiale distribuito con una licenza permissiva, come la MIT o la CC-BY, può essere incluso e distribuito in opere derivate e / o archivi distribuiti sotto altra licenza. 

Per il resto, sono felice che abbiate risolto brillantemente la violazione della licenza di Monitora PA rendendo il vostro progetto indipendente con uno script di scaricamento dedicato. Fintanto che il vostro progetto non dipende da Monitora PA o dai suoi output, non c'è bisogno che cambiate licenza.

**Comment by wohper** [comment]
Grazie per il tuo chiarimento, rimane da capire come sia possibile, cambiando licenza, sottrarre all'utente alcuni diritti garantiti dalla licenza originaria, ovvero poter usufruire e distribuire a sua volta quel contenuto. In più questi sono dati pubblici forniti da un'entità pubblica, rimangono molti dubbi sulla legittimità di poterne restringere l'uso.

Comunque sì, ci siamo resi autonomi e fornito agli utenti un software in grado di ottenere lo stesso dataset con software davvero libero. Siamo hacker e preferiamo offrire strumenti liberi attraverso strutture legali noti, piuttosto che soluzioni amatoriali.

Un saluto!

**Comment by nemobis** [comment]
Il 08/09/22 13:08, Giacomo Tesio ha scritto:
> Stai pubblicamente suggerendo di violare la normativa e i diritti degli autori di Monitora PA abusando la difficoltà di enforcement di tali diritti?

Ovviamente no. Mi limito a segnalare che in giurisdizioni diverse si 
applicano norme diverse. I diritti sui database, in particolare, sono 
scarsamente armonizzati fuori dall'UE (e per fortuna!).
